slam_toolbox:
  ros__parameters:
    # Robot frame setup
    map_frame: map
    base_frame: base_link
    odom_frame: odom
    
    # Scan data source
    scan_topic: /zed2i/zed_node/point_cloud/cloud_registered
    
    # Mapping modes
    mode: mapping # options are mapping (continuous SLAM) and localization (continuous localization)
    map_update_interval: 5.0 # time between map updates
    
    # Optimization configurations
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss
    
    # Loop closure detection
    enable_interactive_mode: false
    loop_search_max_distance: 10.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0 
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45
    
    # Correlation parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 
    
    # Scan matching parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    
    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_scan_matching: true
    use_scan_barycenter: true
    
    # SLAM performance settings
    resolution: 0.05
    max_laser_range: 20.0
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 15.0 
    
    # Debug visualization
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02